[package]
name = "rust_atomics"
version = "0.1.0"
edition = "2024"

[dependencies]


[target.'cfg(loom)'.dependencies]
loom = { version = "0.7", features = ["checkpoint"] }


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)'] }
